app:
  port: 8080

chain:
  rpc: http://127.0.0.1:8545
  contract: 0x67d269191c92Caf3cD7723F116c85e6E9bf55933
  startblock: 0

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123
  dbname: Funding
  sslmode: disable