app:
  port: 8080

chain:
  rpc: http://127.0.0.1:8545
  contract: 0x59b670e9fA9D0A427751Af201D676719a970857b
  startblock: 0

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123
  dbname: Funding
  sslmode: disable